Update testvariable.yml

diff --git a/.github/workflows/testvariable.yml b/.github/workflows/testvariable.yml
--- a/.github/workflows/testvariable.yml
+++ b/.github/workflows/testvariable.yml
@@ -1,4 +1,4 @@
-on: push
+on: issue_comment
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -23,6 +23,7 @@ jobs:
           echo "DoxygenError<<${delimiter}" >> "${GITHUB_OUTPUT}"
           cat artifact.json >> "${GITHUB_OUTPUT}"
           echo "${delimiter}" >> "${GITHUB_OUTPUT}"
+          exit 1
       - name: paste
         run: echo "${{ steps.testenv.outputs.DoxygenError}}"
 
@@ -32,4 +33,16 @@ jobs:
           curl "https://api.github.com/repos/SaillantNicolas/cgal-web/actions/runs/${{ steps.workflowid.outputs.id }}" -o workflow.json
           echo "::set-output name=id::$(cat workflow.json | jq -r '.pull_requests[0].id')"
       - run: echo ${{ steps.prid.outputs.id }}
-    
+      - name: Post error
+        uses: actions/github-script@v6
+        if: ${{ failure() && steps.get_round.outputs.result != 'stop' }}
+        with:
+          script: |
+            const error = "${{steps.testenv.outputs.DoxygenError}}"
+            const msg = "There was an error while building the doc: \n"+error
+            github.rest.issues.createComment({
+              owner: "CGAL",
+              repo: "cgal",
+              issue_number: ${{ github.event.issue.number }},
+              body: msg
+            });
